Repository zxing-js/ngx-scanner, pull requests merged in 2018-04, with the labels that each got.

#57 Updated repo and version
  package.json
Labels: enhancement, priority: high, server: node.js

#59 feat: Torch can be turnt on.
  src/app/modules/zxing-scanner/browser-code-reader.ts
  src/app/modules/zxing-scanner/image-capture.d.ts
  src/app/modules/zxing-scanner/zxing-scanner.component.ts
Labels: enhancement

#61 Add a Gitter chat badge to README.MD
  README.MD
Labels: enhancement, nice to have

#63 Fix: torch
  src/app/modules/zxing-scanner/browser-code-reader.ts
  src/app/modules/zxing-scanner/zxing-scanner.component.ts
Labels: P0, fix, plat: browser

#68 CI build and package tests added
  .travis.yml
  package.json
  src/main.ts
Labels: P0, enhancement, nice to have

#69 Add code of conduct 1
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
Labels: P0, docs, enhancement, nice to have

#72 undefined error if scanner is closed within scanDelay after a success…
  src/app/modules/zxing-scanner/browser-code-reader.ts
Labels: P0

#78 Feature/ssr stability
  .vscode/tasks.json
  ngx-zxing.iml
  package-lock.json
  package.json
  src/app/modules/zxing-scanner/browser-code-reader.ts
  src/app/modules/zxing-scanner/zxing-scanner.component.ts
  yarn.lock
Labels: P0, enhancement, plat: server, server: node.js
