Repository zxing-js/ngx-scanner, pull requests merged in 2018-07, with the labels that each got.

#109 Fixed typo leading to unterminated recursion in restartScan
  src/app/modules/zxing-scanner/zxing-scanner.component.ts
Labels: P0, fix

#112 Support reading different barcode types in develop branch
  .vscode/tasks.json
  README.md
  docs/main.ceff124440b65612fa9c.bundle.js
  src/app/app.component.html
  src/app/modules/zxing-scanner/browser-code-reader.ts
  src/app/modules/zxing-scanner/browser-multi-format-reader.ts
  src/app/modules/zxing-scanner/zxing-scanner.component.ts
Labels: enhancement

#119 Release/v1.2.0
  .vscode/tasks.json
  README.md
  docs/main.ceff124440b65612fa9c.bundle.js
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/modules/zxing-scanner/browser-code-reader.ts
  src/app/modules/zxing-scanner/browser-multi-format-reader.ts
  src/app/modules/zxing-scanner/zxing-scanner.component.html
  src/app/modules/zxing-scanner/zxing-scanner.component.ts
  yarn.lock
Labels: release
