Repository zxing-js/ngx-scanner, pull requests merged in 2019-07, with the labels that each got.

#205 minor changes in init auto start
  projects/zxing-scanner/src/lib/zxing-scanner.component.ts
Labels: enhancement

#221 Release v1.7.2
  projects/zxing-scanner/src/lib/browser-multi-format-continuous-reader.ts
  projects/zxing-scanner/src/lib/zxing-scanner.component.ts
Labels: release

#214 Updated to Angular 8.
  package-lock.json
  package.json
  projects/zxing-scanner-demo/.browserslistrc
  projects/zxing-scanner-demo/browserslist
  projects/zxing-scanner-demo/src/app/app-info-dialog/app-info-dialog.component.ts
  projects/zxing-scanner-demo/src/app/app.component.ts
  projects/zxing-scanner-demo/src/app/app.module.ts
  projects/zxing-scanner-demo/src/app/formats-dialog/formats-dialog.component.ts
  projects/zxing-scanner-demo/src/polyfills.ts
  projects/zxing-scanner/package.json
  projects/zxing-scanner/src/lib/browser-multi-format-continuous-reader.ts
  projects/zxing-scanner/src/lib/image-capture.d.ts
  projects/zxing-scanner/src/lib/zxing-scanner.component.ts
  tsconfig.json
  tslint.json
Labels: enhancement

#223 Release v2.0.0
  package-lock.json
  package.json
  projects/zxing-scanner-demo/.browserslistrc
  projects/zxing-scanner-demo/browserslist
  projects/zxing-scanner-demo/src/app/app-info-dialog/app-info-dialog.component.ts
  projects/zxing-scanner-demo/src/app/app.component.ts
  projects/zxing-scanner-demo/src/app/app.module.ts
  projects/zxing-scanner-demo/src/app/formats-dialog/formats-dialog.component.ts
  projects/zxing-scanner-demo/src/polyfills.ts
  projects/zxing-scanner/package.json
  projects/zxing-scanner/src/lib/browser-multi-format-continuous-reader.ts
  projects/zxing-scanner/src/lib/image-capture.d.ts
  projects/zxing-scanner/src/lib/zxing-scanner.component.ts
  tsconfig.json
  tslint.json
Labels: release

#225 Bugfix/travis deploy
  .travis.yml
Labels: fix

#228 feat: increased version of zxing dependency to enable fixes provided …
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: enhancement

#229 Release/v2.0.1
  package-lock.json
  package.json
  projects/zxing-scanner/package.json
Labels: release
